FROM node:16.16.0 as node

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=node /app/dist/angular-app /usr/share/nginx/html
COPY robots.txt /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/config.conf /etc/nginx/conf.d
