# Stage 0, "node", based on Node.js, to build and compile the frontend
FROM node:16.16.0 as node
ARG configuration=production
WORKDIR /app
COPY ./ /app/
RUN npm install
RUN npm run build -- --output-path=./dist/angular-app --configuration $configuration
# Stage 1, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:alpine
COPY --from=node /app/dist/angular-app /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
# Copy the default nginx.conf provided by node:16.16.0
COPY nginx/config.conf /etc/nginx/conf.d
